### ISSUE TITLE
What to do to get to Addon manager?

### ISSUE THREAD

**Issue by VallesMarinerisExplorer** [alexneufeld/FreeCAD_vendor_parts#3]
Hi!

This seems like a great workbench! I would be interested in contributing! What would it take to get this into the Addon manager? Is there additional development required? Let me know how I can help!

Thanks!

Alex

**Comment by alexneufeld** [comment]
Addon manager support was a tedious bit of work that I'd been putting off. It's done now. Any other contributions you can think of are always welcomed.

**Comment by VallesMarinerisExplorer** [comment]
Awesome!

Great project! I will start using it and see if I have any ideas for improvement.

Thanks again!
